import foundation from './foundation-plan.json' with {type:'json'};
import {mealTotalsMatch,type Meals} from './meals';
export type Profile = { planRevision?:number; paceStart?:string; paceWeight?:number; weight:number; height:number; age:number; start:string; adjustment:number; baselineWeight:number; bodyFat:number; baselineDate:string };
export type Entry = { weight:number|null; bodyFat:number|null; sleep:number|null; soreness:number; pain:boolean; extra:number; calories:number|null; protein:number|null; carbs:number|null; fat:number|null; cardio:number|null; cardioOther?:number|null; notes:string; done:string[]; lifts:Record<string,string>; sets?:Record<string,number>; loads?:Record<string,number>; activityComplete?:boolean; foodComplete?:boolean; meals?:Meals; nutritionTarget?:{calories:number;protein:number;carbs:number;fat:number} };
export const defaultProfile:Profile={planRevision:1,paceStart:'2026-09-08',paceWeight:114,weight:114,height:185,age:26,start:'2026-09-08',adjustment:0,baselineWeight:112,bodyFat:30,baselineDate:'2026-09-08'};
export const emptyEntry=():Entry=>({weight:null,bodyFat:null,sleep:null,soreness:0,pain:false,extra:0,calories:null,protein:null,carbs:null,fat:null,cardio:null,notes:'',done:[],lifts:{}});
export function dateKey(d=new Date()){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Bangkok',year:'numeric',month:'2-digit',day:'2-digit'}).format(d)}
export const days=['จันทร์','อังคาร','พุธ','พฤหัสบดี','ศุกร์','เสาร์','อาทิตย์'];
export type Exercise={id:string;name:string;sets:number;reps:string;cue:string;rest:number;restLabel:string;intensity:string;power?:boolean;main?:boolean;optional?:boolean;legExtra?:boolean};
export const plans=foundation;
export function cycleWeek(week:number){return Math.min(6,Math.max(1,week))}
export function cardioPlan(day:number,week:number,mode:string,extra=0){return {minutes:0,optional:0,text:plans[day].cardio}}
export function exerciseIntensity(ex:Exercise,week:number){if(!ex.power&&(week<=2||week>=6)){const upper=Number(ex.intensity.match(/RPE (\d+)(?:[–-](\d+))?/)?.[2]??ex.intensity.match(/RPE (\d+)/)?.[1]);if(upper>6)return 'RPE 6 (cap)'}return ex.intensity}
export function variation(ex:Exercise,week:number){if(ex.id==='jumpstick')return week<=2?'Weeks 1–2: quick squat-to-calf raise, without leaving the floor. Same sets and reps.':'From week 3: low bilateral jumps only when walking, stairs and landing practice are comfortable; otherwise use the non-jumping version.';if(ex.id==='lateralstick')return week<=2?'Weeks 1–2: lateral step-and-stick; no bound.':'Small lateral bounds only after bilateral landings are consistently controlled and symptom-free during and the following day. Otherwise keep step-and-stick.';return ''}
export function dayIndex(date:string){return (new Date(date+'T12:00:00+07:00').getUTCDay()+6)%7}
export function weekNumber(date:string,start:string){return Math.max(1,Math.floor((Date.parse(date)-Date.parse(start))/604800000)+1)}
export function readiness(e:Entry){return e.pain?'stop':(e.sleep!==null&&e.sleep<6)||e.soreness>=7?'light':'normal'}
export function setCount(exercise:Exercise,week:number,mode:string,day:number){if(mode==='stop')return 0;const base=week>=6?Math.ceil(exercise.sets/2):week<=2&&!exercise.power?Math.min(2,exercise.sets):exercise.sets;return mode==='light'?Math.min(1,base):base}
export function nutrition(p:Profile,day:number,extra:number,proteinWeight=p.weight){const bmr=10*p.weight+6.25*p.height-5*p.age+5;const base=Math.round((bmr*1.45-600)/50)*50;const calories=base+(day===5?200:day===2?-300:0)+(day!==5&&extra>=30?150:0)+p.adjustment;const protein=Math.round(proteinWeight*2*10)/10;const fat=Math.round(calories*.26/5/9)*5;const carbs=Math.round((calories-protein*4-fat*9)/4);return {calories,protein,fat,carbs,proteinWeight,bmr:Math.round(bmr),maintenance:Math.round(bmr*1.45)}}
export function weeklyReview(logs:Record<string,Entry>,date:string){const end=Date.parse(date);const group=(lo:number,hi:number)=>Object.entries(logs).filter(([d,e])=>e.weight!==null&&end-Date.parse(d)>=lo*86400000&&end-Date.parse(d)<hi*86400000).map(([,e])=>e.weight!);const now=group(0,7),prev=group(7,14);const mean=(a:number[])=>a.reduce((s,n)=>s+n,0)/a.length;return {now:now.length?mean(now):null,prev:prev.length?mean(prev):null,delta:now.length>=3&&prev.length>=3?mean(now)-mean(prev):null,n:now.length,p:prev.length}}
export function validDate(value:unknown):value is string{return typeof value==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(value)&&!Number.isNaN(Date.parse(value))&&new Date(value).toISOString().slice(0,10)===value}
function range(v:unknown,min:number,max:number,nullable=false){return nullable&&v===null||typeof v==='number'&&Number.isFinite(v)&&v>=min&&v<=max}
export function validateProfile(p:any):p is Profile{return p&&(p.paceStart===undefined||validDate(p.paceStart))&&(p.paceWeight===undefined||range(p.paceWeight,40,250))&&(p.planRevision===undefined||p.planRevision===1)&&range(p.weight,40,250)&&range(p.height,130,220)&&range(p.age,18,80)&&Number.isInteger(p.age)&&validDate(p.start)&&range(p.adjustment,-200,200)&&range(p.baselineWeight,40,250)&&range(p.bodyFat,5,60)&&validDate(p.baselineDate)}
export function validateEntry(e:any):e is Entry{return e&&(e.nutritionTarget===undefined||e.nutritionTarget&&typeof e.nutritionTarget==='object'&&!Array.isArray(e.nutritionTarget)&&['calories','protein','carbs','fat'].every(k=>range(e.nutritionTarget[k],0,k==='calories'?10000:1500)))&&(e.cardioOther===undefined||range(e.cardioOther,0,360,true))&&(e.loads===undefined||e.loads&&typeof e.loads==='object'&&!Array.isArray(e.loads)&&Object.keys(e.loads).length<=60&&Object.entries(e.loads).every(([k,v])=>/^[a-z]+$/.test(k)&&typeof v==='number'&&Number.isFinite(v)&&v>=0&&v<=1000))&&(e.sets===undefined||e.sets&&typeof e.sets==='object'&&!Array.isArray(e.sets)&&Object.keys(e.sets).length<=60&&Object.entries(e.sets).every(([k,v])=>/^[a-z]+$/.test(k)&&typeof v==='number'&&Number.isInteger(v)&&v>=0&&v<=12))&&(e.foodComplete===undefined||typeof e.foodComplete==='boolean')&&mealTotalsMatch(e)&&range(e.weight,40,250,true)&&range(e.bodyFat,5,60,true)&&range(e.sleep,0,24,true)&&range(e.soreness,0,10)&&typeof e.pain==='boolean'&&range(e.extra,0,360)&&(e.activityComplete===undefined||typeof e.activityComplete==='boolean')&&range(e.calories,0,10000,true)&&['protein','carbs','fat'].every(k=>range(e[k],0,1500,true))&&range(e.cardio,0,360,true)&&typeof e.notes==='string'&&e.notes.length<=1500&&Array.isArray(e.done)&&e.done.length<=30&&e.done.every((s:unknown)=>typeof s==='string'&&/^[a-z]+$/.test(s))&&e.lifts&&typeof e.lifts==='object'&&!Array.isArray(e.lifts)&&Object.keys(e.lifts).length<=60&&Object.entries(e.lifts).every(([k,v])=>/^[a-z]+-\d$/.test(k)&&typeof v==='string'&&v.length<=40)}
export function projection(p:Profile,date:string){const weeks=Math.max(0,(Date.parse(date)-Date.parse(p.baselineDate))/604800000);const lean=p.baselineWeight*(1-p.bodyFat/100);const target=lean/.9;const low=Math.max(target,p.baselineWeight-weeks*.7),high=Math.max(target,p.baselineWeight-weeks*.4);return {low,high,bfLow:Math.max(10,(1-lean/low)*100),bfHigh:Math.max(10,(1-lean/high)*100),target,weeks}}

export function compositionScenario(p:Profile){const lean=p.baselineWeight*(1-p.bodyFat/100);return {lean,atWeights:[90,95].map(weight=>({weight,bodyFat:(1-lean/weight)*100})),atBodyFats:[20,15,10].map(bodyFat=>({bodyFat,weight:lean/(1-bodyFat/100)}))}}

// Apply the latest user-reported calculation weight once; preserve the separately dated BF baseline.
export function currentProfile(p:Profile):Profile{return p.planRevision===1?{...defaultProfile,...p}:{...defaultProfile,...p,weight:114,paceWeight:114,paceStart:'2026-09-08',planRevision:1}}

export function proteinWeightForDate(p:Profile,logs:Record<string,Entry>,date:string,entry:Entry){
 const usable=(w:number|null):w is number=>typeof w==='number'&&Number.isFinite(w)&&w>=40&&w<=250;
 if(usable(entry.weight))return entry.weight;
 const latest=Object.entries(logs).filter(([d,e])=>d<=date&&usable(e.weight)).sort(([a],[b])=>b.localeCompare(a))[0];
 return latest?latest[1].weight!:p.weight;
}
