'use client';
import {useState} from 'react';
import {ChevronLeft,ChevronRight,ArrowUpRight} from 'lucide-react';
import GoalOutlook,{GoalHeadline} from './goal-outlook';
import WeeklyCoach from './weekly-coach';
import {dayIndex,plans,weekNumber,cycleWeek,cardioPlan,setCount,type Profile,type Entry} from '@/lib/coach';
const short=['Lower','Upper','Full rest','Full body','Light support','Badminton','Easy movement'];
export default function Calendar({profile,date,logs,onChoose}:{profile:Profile;date:string;logs:Record<string,Entry>;onChoose:(date:string)=>void}){
 const [month,setMonth]=useState(date.slice(0,7));
 const first=month+'-01',offset=dayIndex(first),count=new Date(Number(month.slice(0,4)),Number(month.slice(5)),0).getDate();
 const change=(n:number)=>{const d=new Date(first+'T12:00:00Z');d.setUTCMonth(d.getUTCMonth()+n);setMonth(d.toISOString().slice(0,7))};
 return <><GoalHeadline profile={profile}/><section className="panel calendar-panel"><div className="section-head"><div><p className="eyebrow">TRAINING CALENDAR</p><h2>ภาพรวมทั้งเดือน</h2></div><div className="date-controls"><button onClick={()=>change(-1)} aria-label="เดือนก่อนหน้า"><ChevronLeft size={18}/></button><label><span className="sr-only">เลือกเดือน</span><input type="month" value={month} min="2026-01" max="2027-12" onChange={e=>{if(e.target.value)setMonth(e.target.value)}}/></label><button onClick={()=>change(1)} aria-label="เดือนถัดไป"><ChevronRight size={18}/></button></div></div><p className="muted">Five gym days, eight exercises each · Wednesday full rest · Saturday badminton 4 hours including breaks · Six-week foundation block</p><div className="calendar-scroll"><div className="month-grid">{['จ.','อ.','พ.','พฤ.','ศ.','ส.','อา.'].map(s=><b className="weekday" key={s}>{s}</b>)}{Array.from({length:offset},(_,i)=><div className="blank-day" key={'b'+i}/>)}{Array.from({length:count},(_,i)=>{const key=month+'-'+String(i+1).padStart(2,'0'),di=dayIndex(key),p=plans[di],wk=weekNumber(key,profile.start),cp=cardioPlan(di,wk,'normal'),log=logs[key],before=key<profile.start;return <button disabled={before} key={key} className={'calendar-day day-'+di+(key===date?' chosen':'')} onClick={()=>onChoose(key)}><div><strong>{i+1}</strong>{log&&<span className="saved-dot" aria-label="มีบันทึก"/>}</div><b>{before?'ก่อนเริ่มแผน':short[di]}</b>{!before&&<><span className="calendar-moves">{p.exercises.length?p.exercises.slice(0,2).map(e=>e.name).join(' / '):di===5?'4 hours including breaks':'Full rest'}</span><span>{p.exercises.length>2?`+ ${p.exercises.length-2} ท่า · `:''}{p.exercises.length?'เผื่อเวลา ':''}{di===2?'Full rest':p.time+' นาที'}</span>{p.exercises.length>0&&<span>{p.exercises.reduce((n,e)=>n+setCount(e,wk,'normal',di),0)} เซ็ต · คาร์ดิโอ {cp.minutes} นาที{cp.optional?' / เลือก 60 ได้':''}</span>}{cycleWeek(wk)===6&&<span>สัปดาห์ผ่อน</span>}{log?.weight!=null&&<small className="actual">วัดจริง {log.weight} กก.{log.bodyFat!=null?` / ${log.bodyFat}%`:''}</small>}</>}</button>})}</div></div></section><WeeklyCoach profile={profile} logs={logs} date={date}/><GoalOutlook profile={profile} logs={logs} date={date}/></>
}
