'use client';
import {useState} from 'react';
import {parseData,encodeBackup,mergeImport,type LocalData} from '@/lib/local-store';
export function downloadJson(text:string,name:string){const url=URL.createObjectURL(new Blob([text],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export default function DataTools({data,canImport,onImport,onReload,exportData,recoveryRaw}:{data:LocalData;canImport:boolean;onImport:(data:LocalData)=>Promise<void>;recoveryRaw?:string|null;onReload:()=>void;exportData:()=>LocalData}){
 const [busy,setBusy]=useState(false);
 const [pending,setPending]=useState<LocalData|null>(null),[message,setMessage]=useState(''),[overwrite,setOverwrite]=useState(false),[useProfile,setUseProfile]=useState(false);
 const duplicates=pending?Object.keys(pending.logs).filter(d=>Object.hasOwn(data.logs,d)).length:0;
 function saveBackup(){try{downloadJson(encodeBackup(exportData()),'court-coach-'+new Date().toISOString().slice(0,10)+'.backup.json');setMessage('ส่งออกข้อมูลแล้ว เก็บไฟล์นี้ไว้ส่วนตัว')}catch(e){setMessage((e as Error).message)}}
 return <section className="panel data-tools" id="data-tools"><h3>ข้อมูลในเครื่องและไฟล์สำรอง</h3><p>เก็บบนเบราว์เซอร์นี้ ไม่ต้องเข้าสู่ระบบ ไม่ซิงก์ข้ามเครื่องอัตโนมัติ การล้างข้อมูลเว็บอาจลบบันทึก ควรส่งออกเป็นระยะ</p>{recoveryRaw!=null&&<p className="notice">ข้อมูลในเครื่องอ่านไม่ได้ คุณสามารถเลือกไฟล์สำรองที่ถูกต้องเพื่อกู้คืน การยืนยันจะดาวน์โหลดข้อมูลที่อ่านไม่ได้ก่อน แล้วใช้ไฟล์ที่เลือกแทน</p>}<div className="data-actions"><button className="action" onClick={saveBackup}>ส่งออกข้อมูล JSON</button><label className="action secondary">เลือกไฟล์เพื่อนำเข้า<input className="sr-only" type="file" accept=".json,application/json" onChange={async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;try{if(file.size>5_000_000)throw Error('ไฟล์ใหญ่เกิน 5 MB');const parsed=parseData(await file.text());setPending(parsed);setOverwrite(false);setUseProfile(!data.profile);setMessage('ตรวจไฟล์แล้ว ยังไม่เปลี่ยนข้อมูลในเครื่อง')}catch(err){setPending(null);setMessage((err as Error).message)}}}/></label><button className="small-btn" onClick={onReload}>โหลดข้อมูลในเครื่องใหม่</button></div>{pending&&<div className="notice"><h4>ตรวจรายการก่อนนำเข้า</h4><p>มี {Object.keys(pending.logs).length} วัน · ซ้ำกับในเครื่อง {duplicates} วัน · {pending.profile?'มีข้อมูลส่วนตัว':'ไม่มีข้อมูลส่วนตัว'}</p><label className="checkline"><input type="checkbox" checked={overwrite} onChange={e=>setOverwrite(e.target.checked)}/>ใช้ข้อมูลในไฟล์แทนวันที่ซ้ำ (ปกติเก็บของในเครื่อง)</label>{pending.profile&&<label className="checkline"><input type="checkbox" checked={useProfile} onChange={e=>setUseProfile(e.target.checked)}/>ใช้ข้อมูลส่วนตัวและตั้งค่าแผนจากไฟล์</label>}<p className="muted">ก่อนนำเข้า ระบบจะดาวน์โหลดสำเนาข้อมูลปัจจุบัน วันอื่นจะยังคงอยู่</p><div className="data-actions"><button className="action" disabled={!canImport||busy} onClick={async()=>{setBusy(true);try{const merged=mergeImport(data,pending,overwrite,useProfile);downloadJson(recoveryRaw??encodeBackup(data),'court-coach-before-import.backup.json');await onImport(merged);setPending(null);setMessage('นำเข้าและบันทึกในเครื่องเรียบร้อยแล้ว')}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}}>ยืนยันนำเข้า</button><button className="small-btn" onClick={()=>setPending(null)}>ยกเลิก</button></div>{!canImport&&<p>บันทึกวันที่แก้ไขและข้อมูลส่วนตัวให้เรียบร้อยก่อนนำเข้า</p>}</div>}{message&&<p role="status">{message}</p>}<p className="muted">ส่งออกรวมวันที่กรอกค้างอยู่เมื่อค่าถูกต้อง นำเข้ารองรับไฟล์สำรองรุ่นนี้และ JSON จากเว็บ Sites เดิม ไม่อัปโหลดไฟล์ไปที่เซิร์ฟเวอร์</p></section>
}
