import {useState} from 'react';
import type {FoodPreset} from '@/lib/food-presets';
export default function EditRecipe({food,onSave,onCancel}:{food:FoodPreset;onSave:(food:FoodPreset)=>void;onCancel:()=>void}){
 const [error,setError]=useState('');
 function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget);try{
  const values=Object.fromEntries(['calories','protein','carbs','fat'].map(k=>[k,data.get(k)===''?null:Number(data.get(k))])) as FoodPreset['values'];
  onSave({...food,name:String(data.get('name')).trim(),unit:String(data.get('unit')).trim(),ingredients:String(data.get('ingredients')).split('\n').map(s=>s.trim()).filter(Boolean),method:String(data.get('method')),values,logNote:undefined,sources:undefined,estimate:'Edited by you · nutrition per serving. Blank values are unknown.'});onCancel();
 }catch(e){setError((e as Error).message)}}
 return <form className="panel recipe-editor" onSubmit={submit}><h3>Edit recipe</h3><label className="field">Menu name<input name="name" required maxLength={120} defaultValue={food.name}/></label><label className="field">Serving<input name="unit" required maxLength={40} defaultValue={food.unit}/></label><label className="field">Ingredients / portion details<textarea name="ingredients" maxLength={10000} rows={6} defaultValue={food.ingredients.join('\n')}/></label><label className="field">Preparation / notes<textarea name="method" maxLength={2000} rows={4} defaultValue={food.method}/></label><div className="formgrid two">{[['calories','Energy (kcal)'],['protein','Protein (g)'],['carbs','Carbs (g)'],['fat','Fat (g)']].map(([key,label])=><label className="field" key={key}>{label}<input name={key} type="number" min={0} max={key==='calories'?10000:1500} step="any" defaultValue={food.values[key as keyof typeof food.values]??''}/></label>)}</div><p>Update nutrition per serving when changing ingredients. Ingredient text does not automatically recalculate nutrition.</p><p className="muted">Saved in this browser. Future meal selections use this recipe; existing daily records keep their recorded values.</p>{error&&<p role="alert">{error}</p>}<button className="action" type="submit">Save recipe</button> <button type="button" onClick={onCancel}>Cancel editing</button></form>
}
