import AddMenuItem from './add-menu-item';
import EditRecipe from './edit-recipe';
'use client';
import {useState} from 'react';
import {MoreVertical} from 'lucide-react';
import {foodPresets,foodSource,type FoodPreset} from '@/lib/food-presets';

export default function FoodLibrary({onChoose,onAdd,onEdit,foods:allFoods=foodPresets,error}:{onChoose:(id:string)=>void;onAdd:(item:FoodPreset)=>void;onEdit:(item:FoodPreset)=>void;foods?:FoodPreset[];error?:string}){
 const [query,setQuery]=useState(''),[editing,setEditing]=useState<string|null>(null);
 const foods=allFoods.filter(f=>(f.name+' '+f.ingredients.join(' ')).toLowerCase().includes(query.trim().toLowerCase()));
 function beginEdit(id:string){setEditing(id);requestAnimationFrame(()=>document.querySelector('.recipe-editor')?.scrollIntoView({behavior:'smooth',block:'start'}))}
 return <section className="food-library"><div className="food-library-head"><div><h2>สูตรที่คุณกินประจำ</h2><p>เลือกสูตร ดูปริมาณ แล้วใช้บันทึกมื้ออาหารใน Home</p></div><a href={foodSource} target="_blank" rel="noreferrer">ดูแชตต้นทาง ↗</a></div><AddMenuItem onAdd={onAdd}/>{editing&&allFoods.find(f=>f.id===editing)&&<EditRecipe key={editing} food={allFoods.find(f=>f.id===editing)!} onSave={onEdit} onCancel={()=>setEditing(null)}/>} {error&&<p role="alert">{error}</p>}<label className="field food-search">ค้นหาสูตรหรือวัตถุดิบ<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="เช่น โอ๊ต กะเพรา อกไก่"/></label><div className="food-recipe-grid">{foods.map(food=><article className="panel food-recipe" key={food.id}><span className="pill">{food.tag} · ต่อ 1 {food.unit}</span><details className="recipe-menu"><summary aria-label={`Recipe options: ${food.name}`}><MoreVertical size={19} aria-hidden="true"/></summary><div className="recipe-menu-popover"><button type="button" onClick={e=>{e.preventDefault();beginEdit(food.id)}}>Edit recipe</button></div></details><h3>{food.name}</h3><div className="recipe-energy">{food.values.calories??'—'} <small>kcal โดยประมาณ</small></div><div className="recipe-macros"><span>โปรตีน <b>{food.values.protein??'—'} g</b></span><span>คาร์บ <b>{food.values.carbs??(food.id==='oats-less-carb'&&!food.estimate.startsWith('Edited by you')?'48–50':'—')} g</b></span><span>ไขมัน <b>{food.values.fat??'—'} g</b></span></div><p className="muted">{food.estimate}</p><details><summary>วัตถุดิบและวิธีเตรียม</summary><ul>{food.ingredients.map(i=><li key={i}>{i}</li>)}</ul><p>{food.method}</p>{food.sources&&<p>แหล่งอ้างอิง: {food.sources.map(s=><a key={s.url} href={s.url} target="_blank" rel="noreferrer">{s.title} ↗ </a>)}</p>}</details><button className="action" onClick={()=>onChoose(food.id)}>เลือกสูตรนี้ใน Home</button></article>)}</div>{foods.length===0&&<p className="notice">ไม่พบสูตร ลองค้นหาด้วยชื่อวัตถุดิบอื่น</p>}<p className="muted">เมนูใน Home และหน้านี้ใช้คลังสูตรเดียวกัน • สารอาหารเป็นค่าประมาณตามปริมาณในสูตร แรปและซอสยังต้องเทียบฉลากจริง • เลือกสูตรแล้วแก้ยอดจริงได้</p></section>
}
