'use client';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {compositionScenario,weeklyReview,type Profile,type Entry} from '@/lib/coach';
export function GoalHeadline({profile}:{profile:Profile}){
 return <div className="goalstrip"><div><p className="eyebrow">จุดเริ่มต้น · {profile.baselineDate}</p><b>{profile.baselineWeight} กก. <span>/ BF {profile.bodyFat}%</span></b></div><div><p className="eyebrow">สิ้นปี · เป้าหมายที่ตั้งไว้</p><b>90–95 กก.</b><span>31 ธันวาคม 2026 · ไม่ใช่น้ำหนักที่ทำนาย</span></div><div><p className="eyebrow">BEST CASE · เป้าท้าทาย</p><b>BF 10%</b><span>เป้าสิ้นปีที่อยากไปถึง · ยังรับประกันไม่ได้</span></div></div>
}
export default function GoalOutlook({profile,logs,date}:{profile:Profile;logs:Record<string,Entry>;date:string}){
 const x=compositionScenario(profile),review=weeklyReview(logs,date);
 return <div className="two-panels"><section className="panel"><p className="eyebrow">WEIGHT & BODY FAT</p><h3>90–95 กก. เท่ากับ BF เท่าไร?</h3><p>จากข้อมูลตั้งต้น มวลไร้ไขมันประมาณ <b>{x.lean.toFixed(1)} กก.</b> หากรักษาไว้ได้ทั้งหมด จะคำนวณได้ดังนี้</p><Table className="bodyfat-table"><TableHeader><TableRow><TableHead>สถานการณ์</TableHead><TableHead>น้ำหนัก</TableHead><TableHead>Body Fat</TableHead></TableRow></TableHeader><TableBody>{x.atWeights.map(row=><TableRow key={row.weight}><TableCell>น้ำหนักเป้าหมาย</TableCell><TableCell>{row.weight} กก.</TableCell><TableCell>{row.bodyFat.toFixed(1)}%</TableCell></TableRow>)}{x.atBodyFats.map(row=><TableRow key={row.bodyFat}><TableCell>{row.bodyFat===10?'Best case ที่ตั้งไว้':'จุดเปรียบเทียบ'}</TableCell><TableCell>{row.weight.toFixed(1)} กก.</TableCell><TableCell>{row.bodyFat}%</TableCell></TableRow>)}</TableBody></Table><p className="muted">ตารางนี้แปลงน้ำหนักกับ BF ภายใต้สมมติฐานมวลไร้ไขมันคงเดิม ไม่ใช่ผลลัพธ์ที่แผนรับประกันหรือเส้นที่ต้องเร่งไล่ให้ทัน มวลไร้ไขมันรวมกล้าม น้ำ กระดูก และเนื้อเยื่ออื่นด้วย</p><p>หากมวลไร้ไขมันลดไป 2 กก. ที่น้ำหนัก 95 กก. BF จะเป็นประมาณ {((1-(x.lean-2)/95)*100).toFixed(1)}% จึงต้องติดตามแรงเวทและการฟื้นตัวควบคู่ ไม่ดูน้ำหนักอย่างเดียว</p></section><section className="panel"><p className="eyebrow">EXPECTED OUTCOME</p><h3>ถ้าทำตามแผนครบ จะถึง 10% หรือ 15–20%?</h3><p><b>ยังสรุปไม่ได้ว่าแผนนี้จะพาไปถึงช่วงใดภายในสิ้นปี</b> แม้ทำครบ BF ก็อาจยังสูงกว่า 20% เพราะพลังงานที่ใช้จริง การกิน การฟื้นตัว และการเปลี่ยนแปลงมวลไร้ไขมันต่างกันในแต่ละคน</p><p>BF 15–20% เทียบเท่าน้ำหนักประมาณ <b>{x.atBodyFats[1].weight.toFixed(1)}–{x.atBodyFats[0].weight.toFixed(1)} กก.</b> ภายใต้สมมติฐานเดิม ส่วน BF 10% เทียบเท่าประมาณ <b>{x.atBodyFats[2].weight.toFixed(1)} กก.</b> เป้า 90–95 กก. และ best case 10% จึงไม่ใช่ผลเดียวกันโดยอัตโนมัติ</p><div className="coach-note"><b>ข้อมูลจริง ณ วันที่เลือก · {date}</b><p>{review.now===null?'ยังไม่มีน้ำหนักเฉลี่ยที่บันทึก':`น้ำหนักเฉลี่ย 7 วัน ${review.now.toFixed(1)} กก. จาก ${review.n} วัน`}</p><p>{review.delta===null?'บันทึกอย่างน้อย 3 วันในแต่ละช่วง 7 วัน แล้วติดตามต่อ 3–4 สัปดาห์เพื่อเริ่มประเมินการตอบสนอง':`เปลี่ยนจากค่าเฉลี่ย 7 วันก่อน ${review.delta>0?'+':''}${review.delta.toFixed(2)} กก. แนวโน้มระยะสั้นนี้ยังไม่ควรลากเป็นเส้นตรงถึงสิ้นปี`}</p></div><p>เป้า 90–95 กก. ต้องลด {Math.max(0,profile.baselineWeight-95).toFixed(1)}–{Math.max(0,profile.baselineWeight-90).toFixed(1)} กก. ในเวลาที่เหลือ เป็นเป้าท้าทายที่ควรทบทวนร่วมกับผู้เชี่ยวชาญ ไม่ลดอาหารหรือเพิ่มคาร์ดิโออัตโนมัติเมื่อหลุดเป้า</p></section></div>
}
