'use client';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {paceReference,coachingReview} from '@/lib/weekly-coach';
import type {Profile,Entry} from '@/lib/coach';
export default function WeeklyCoach({profile,logs,date}:{profile:Profile;logs:Record<string,Entry>;date:string}){
 const end=paceReference(profile,'2026-12-31'),r=coachingReview(logs,date);
 const months=['2026-09-30','2026-10-31','2026-11-30','2026-12-31'].filter(d=>d>=(profile.paceStart??profile.baselineDate));
 return <section className="panel weekly-coach"><p className="eyebrow">WEEKLY COACH · เป้ารายสัปดาห์</p><h2>ตั้งใจลดเฉลี่ยใกล้ 1 กก./สัปดาห์</h2><p>เป็นเป้าที่คุณตั้งไว้เพื่อทบทวนผล ไม่ใช่คำรับประกันหรือขั้นต่ำที่ต้องเร่งให้ถึง ลดเร็วกว่านี้ไม่ได้ดีกว่าเสมอ โดยเฉพาะเมื่ออยากให้ขาแข็งแรงและเล่นแบตได้ดี</p><div className="two-panels"><div><h3>เส้นเปรียบเทียบจาก {profile.paceWeight??profile.baselineWeight} กก.</h3><p>เริ่มเส้น {profile.paceStart??profile.baselineDate} · หากลดเฉลี่ย 1 กก./สัปดาห์ตลอด {end.weeks.toFixed(1)} สัปดาห์ถึงสิ้นปี จะเป็น <b>{end.weight.toFixed(1)} กก.</b>{end.bodyFat!==null&&<> และ BF ประมาณ <b>{end.bodyFat.toFixed(1)}%</b> เมื่ออ้างอิงมวลไร้ไขมันเดิมจาก {profile.baselineWeight} กก./{profile.bodyFat}% และสมมติว่ารักษาไว้ได้ทั้งหมด (ยังไม่มี BF คู่กับน้ำหนักล่าสุด)</>} ตัวเลขนี้เป็นสมมติฐาน ไม่ใช่การคาดการณ์เฉพาะตัว</p><Table><TableHeader><TableRow><TableHead>วันที่</TableHead><TableHead>เส้น 1 กก./สัปดาห์</TableHead></TableRow></TableHeader><TableBody>{months.map(d=><TableRow key={d}><TableCell>{d}</TableCell><TableCell>{paceReference(profile,d).weight.toFixed(1)} กก.</TableCell></TableRow>)}</TableBody></Table><p className="muted">ใช้ค่าเฉลี่ยรายสัปดาห์เทียบ ไม่ต้องชั่งได้ตรงเส้นในวันนั้น และไม่เพิ่มการขาดพลังงานเพื่อชดเชยระยะห่างจากเส้น</p></div><div><h3>{r.status}</h3><p>{r.message}</p><div className="coach-note"><b>จากบันทึกที่บันทึกสำเร็จถึง {date}</b><p>น้ำหนัก {r.current.n}/7 วัน · สัปดาห์ก่อน {r.current.p}/7 วัน</p><p>{r.current.delta===null?'ยังเทียบค่าเฉลี่ยไม่ได้':`ค่าเฉลี่ยเปลี่ยน ${r.current.delta>0?'+':''}${r.current.delta.toFixed(2)} กก./สัปดาห์`}</p><p>อาหาร {r.foodDays}/14 วัน · ยืนยันกิจกรรมครบ {r.completeDays}/14 วัน</p></div><p>อาหารในแอปเป็นจุดเริ่มต้นสำหรับเก็บผล 14 วัน ยังไม่ได้พิสูจน์ว่าจะทำให้ลด 1 กก./สัปดาห์ อย่านำ kcal จากนาฬิกามาบวกกินคืนหรือตัดเพิ่มตรง ๆ</p></div></div><details><summary>ภาพกิจกรรมที่คุณส่งบอกอะไรบ้าง</summary><p>ล่าสุดที่แจ้ง: 114 กก. และกินประมาณ 3,000 kcal/วันโดยยังไม่ได้นับละเอียด ใช้ปรับน้ำหนักคำนวณอาหารเป็น 114 กก. แต่ยังไม่สร้างบันทึกน้ำหนักรายวันโดยไม่มีวันที่ชั่งยืนยัน ภาพมีแบตประมาณ 2 ชั่วโมง 26 นาที–3 ชั่วโมง 22 นาที และบางวันมีเวท/ลู่ร่วมด้วย บันทึกที่เห็นเป็นเพียงส่วนหนึ่งตามที่คุณแจ้ง ไม่ใช่กิจกรรมทั้งหมด</p><p>ภาพน้ำหนักมุมมองรายสัปดาห์แสดงเฉลี่ย 113.6 กก. ช่วง 112.6–114.8 กก. แต่ไม่ใช่น้ำหนักเช้าล่าสุด และไม่ได้แสดงค่า BF จึงไม่เขียนทับจุดตั้งต้น 112 กก. / 30% หรือสร้างบันทึกรายวันจากภาพนี้</p><p>เมื่อเล่นแบตนาน ให้บันทึกเวลารวมพักและความหนักในหมายเหตุด้วย ไม่นับทุกนาทีว่าออกแรงต่อเนื่อง วันแบตไม่ต้องเพิ่มลู่เพื่อเร่งน้ำหนัก หากซ้อมยาวเกิน 90–120 นาทีควรวางอาหารและน้ำระหว่างซ้อมให้เหมาะกับเวลาที่ออกแรงจริง</p></details><p className="muted">แนวทางทั่วไปของ <a href="https://www.cdc.gov/healthy-weight-growth/losing-weight/index.html" target="_blank" rel="noreferrer">CDC</a> อยู่ราว 0.45–0.9 กก./สัปดาห์ เป้า 1 กก. จึงอยู่ใกล้ขอบบนและควรทบทวนตามการฟื้นตัว หากต้องการเร่งให้ถึง BF 10% ตามกำหนด ควรวางแผนร่วมกับนักกำหนดอาหารกีฬา/แพทย์</p></section>
}
