'use client';
import {Accordion,AccordionItem,AccordionTrigger,AccordionContent} from '@/components/ui/accordion';
import exerciseImages from '@/lib/exercise-images.json';
import {setCount,type Exercise,type Entry} from '@/lib/coach';
export default function WorkoutList({exercises,entry,edit,week,mode,day}:{exercises:Exercise[];entry:Entry;edit:(e:Partial<Entry>)=>void;week:number;mode:string;day:number}){
 const total=exercises.reduce((sum,e)=>sum+(entry.sets?.[e.id]??0),0);
 return <div className="compact-workouts"><div className="workout-progress"><b>{Object.keys(entry.sets??{}).length?`บันทึกแล้ว ${total} เซ็ต`:'ยังไม่ได้กรอกจำนวนเซ็ต'}</b><span>แตะชื่อท่าเพื่อดูรูปและวิธีเล่น</span></div><Accordion multiple={false} defaultValue={exercises.length?[exercises[0].id]:[]}>
 {exercises.map((ex,i)=>{const target=setCount(ex,week,mode,day),photos=exerciseImages[ex.id as keyof typeof exerciseImages],actual=entry.sets?.[ex.id];const old=Object.entries(entry.lifts).filter(([key])=>key.startsWith(ex.id+'-'));return <AccordionItem value={ex.id} key={ex.id} className={'compact-exercise '+(target>0&&actual!==undefined&&actual>=target?'is-complete':'')}><div className="compact-heading"><AccordionTrigger><span className="exercise-num">{i+1}</span><span className="movement-label"><b>{ex.name}</b><span>{target===0?'พักท่าเสริมวันนี้':target+' เซ็ต × '+ex.reps}{target===0||ex.reps.includes('วินาที')?'':' ครั้ง'}</span>{entry.loads?.[ex.id]!==undefined&&<small>น้ำหนักหลัก {entry.loads[ex.id]} กก.</small>}{ex.optional&&<small>{ex.legExtra?'ท่าเสริมขา · เบาและไม่ฝืน':'ท่าเสริมเมื่อพร้อม'}</small>}</span></AccordionTrigger><label className="actual-sets"><span>ทำจริง (เซ็ต)</span><input type="number" inputMode="numeric" step={1} min={0} max={12} placeholder="—" value={actual??''} aria-label={ex.name+' จำนวนเซ็ตที่ทำจริง'} onChange={event=>{const sets={...entry.sets};if(event.target.value==='')delete sets[ex.id];else sets[ex.id]=Number(event.target.value);const done=target>0&&(sets[ex.id]??0)>=target?[...new Set([...entry.done,ex.id])]:entry.done.filter(id=>id!==ex.id);edit({sets,done});}}/></label></div><AccordionContent><label className="field single-load"><span>น้ำหนักหลักที่ใช้ (กก. · ไม่บังคับ)</span><input type="number" inputMode="decimal" min={0} max={1000} step="any" placeholder="เช่น 15" aria-label={ex.name+' น้ำหนักหลักที่ใช้ กก.'} value={entry.loads?.[ex.id]??''} onChange={event=>{const loads={...entry.loads};if(event.target.value==='')delete loads[ex.id];else loads[ex.id]=Number(event.target.value);edit({loads});}}/><small>กรอกครั้งเดียวต่อท่า: ดัมเบลต่อลูก เครื่องตามหน่วยกก. ที่ระบุ ถ้าใช้หลายกิโลให้ใส่น้ำหนักหลัก และเขียนรายละเอียดเพิ่มในหมายเหตุได้</small></label><div className="exercise-photos">{photos.images.map((src,j)=><figure key={src}><img src={src} alt={ex.name+' จังหวะ '+(j+1)} loading="lazy" width={420} height={300}/><figcaption>จังหวะ {j+1}</figcaption></figure>)}</div><p className="movement-cue">{ex.cue}</p><p className="muted">ใช้แรงต้านที่ทำจำนวนครั้งตามแผนด้วยฟอร์มดี แล้วยังเหลือแรง 2–3 ครั้ง ท่าค้างให้ยึดวินาที ท่าข้างเดียวให้ทำครบสองข้าง</p><p className="rest-guidance"><b>พักประมาณ {ex.rest>=120?ex.rest/60+' นาที':ex.rest+' วินาที'}</b> · กะเวลาได้ พักต่อจนหายใจและฟอร์มพร้อม</p>{old.length>0&&<details className="old-lifts"><summary>บันทึกกิโล/ครั้งเดิมของวันนี้</summary>{old.map(([key,value])=><p key={key}>เซ็ต {Number(key.split('-').at(-1))+1}: {value||'ยังไม่กรอก'}</p>)}</details>}{entry.done.includes(ex.id)&&actual===undefined&&<p className="muted">เคยติ๊กว่าทำครบไว้ แต่ยังไม่มีจำนวนเซ็ตที่กรอก</p>}</AccordionContent></AccordionItem>})}
 </Accordion></div>
}
