'use client';
import {Accordion,AccordionItem,AccordionTrigger,AccordionContent} from '@/components/ui/accordion';
import exerciseImages from '@/lib/exercise-images.json';
import {setCount,exerciseIntensity,variation,type Exercise,type Entry} from '@/lib/coach';
type ExercisePhoto={images:string[];source:string;note?:string;layout?:string;earlyImages?:string[];earlySource?:string;earlyNote?:string;laterImages?:string[];laterSource?:string};
function Photos({photo,name,week}:{photo:ExercisePhoto;name:string;week:number}){const early=week<=2&&photo.earlyImages,images=early||photo.images;return <div className="movement-visual">{(early?photo.earlyNote:photo.note)&&<p className="image-note">{early?photo.earlyNote:photo.note}</p>}<div className={'exercise-photos '+(images.length===1?'combined-poses':'')} >{images.map((src,i)=><figure key={src}><a href={src} target="_blank" rel="noreferrer" aria-label={'Enlarge '+name+' reference '+(i+1)}><img src={src} alt={name+(images.length===1?' — movement demonstration':' — position '+(i+1))} loading="lazy"/></a><figcaption>{images.length===1?(photo.layout==='animation'?'Movement demonstration':'Start and finish · tap to enlarge'):'Position '+(i+1)}</figcaption></figure>)}</div><a className="image-source" href={early?photo.earlySource:photo.source} target="_blank" rel="noreferrer">Image source</a>{week>=3&&photo.laterImages&&<details><summary>Later progression: small lateral bound</summary><p>Only after bilateral landings are consistently controlled and symptom-free during and the following day. Keep the bound small; hold the landing.</p><div className="exercise-photos combined-poses">{photo.laterImages.map(src=><figure key={src}><img src={src} alt="Small lateral bound — later progression only" loading="lazy"/></figure>)}</div><a href={photo.laterSource} target="_blank" rel="noreferrer">Image source</a></details>}</div>}
export default function WorkoutList({exercises,entry,edit,week,mode,day}:{exercises:Exercise[];entry:Entry;edit:(e:Partial<Entry>)=>void;week:number;mode:string;day:number}){
 const total=exercises.reduce((sum,e)=>sum+(entry.sets?.[e.id]??0),0);
 return <div className="compact-workouts"><div className="workout-progress"><b>{Object.keys(entry.sets??{}).length?`บันทึกแล้ว ${total} เซ็ต`:'ยังไม่ได้กรอกจำนวนเซ็ต'}</b><span>แตะชื่อท่าเพื่อดูรูปและวิธีเล่น</span></div><Accordion multiple={false} defaultValue={exercises.length?[exercises[0].id]:[]}>
 {exercises.map((ex,i)=>{const target=setCount(ex,week,mode,day),photos=exerciseImages[ex.id as keyof typeof exerciseImages],actual=entry.sets?.[ex.id];const old=Object.entries(entry.lifts).filter(([key])=>key.startsWith(ex.id+'-'));return <AccordionItem value={ex.id} key={ex.id} className={'compact-exercise '+(target>0&&actual!==undefined&&actual>=target?'is-complete':'')}><div className="compact-heading"><AccordionTrigger><span className="exercise-num">{i+1}</span><span className="movement-label"><b>{ex.name}</b><span>{target===0?'Rest':target+' sets × '+ex.reps}</span><small>{exerciseIntensity(ex,week)}</small>{entry.loads?.[ex.id]!==undefined&&<small>น้ำหนักหลัก {entry.loads[ex.id]} กก.</small>}{ex.optional&&<small>{ex.legExtra?'ท่าเสริมขา · เบาและไม่ฝืน':'ท่าเสริมเมื่อพร้อม'}</small>}</span></AccordionTrigger><label className="actual-sets"><span>ทำจริง (เซ็ต)</span><input type="number" inputMode="numeric" step={1} min={0} max={12} placeholder="—" value={actual??''} aria-label={ex.name+' จำนวนเซ็ตที่ทำจริง'} onChange={event=>{const sets={...entry.sets};if(event.target.value==='')delete sets[ex.id];else sets[ex.id]=Number(event.target.value);const done=target>0&&(sets[ex.id]??0)>=target?[...new Set([...entry.done,ex.id])]:entry.done.filter(id=>id!==ex.id);edit({sets,done});}}/></label></div><AccordionContent>{variation(ex,week)&&<p className="notice">{variation(ex,week)}</p>}{photos&&<Photos photo={photos} name={ex.name} week={week}/>}<p className="movement-cue">{ex.cue}</p><label className="field single-load"><span>น้ำหนักหลักที่ใช้ (กก. · ไม่บังคับ)</span><input type="number" inputMode="decimal" min={0} max={1000} step="any" placeholder="เช่น 15" aria-label={ex.name+' น้ำหนักหลักที่ใช้ กก.'} value={entry.loads?.[ex.id]??''} onChange={event=>{const loads={...entry.loads};if(event.target.value==='')delete loads[ex.id];else loads[ex.id]=Number(event.target.value);edit({loads});}}/><small>กรอกครั้งเดียวต่อท่า: ดัมเบลต่อลูก เครื่องตามหน่วยกก. ที่ระบุ ถ้าใช้หลายกิโลให้ใส่น้ำหนักหลัก และเขียนรายละเอียดเพิ่มในหมายเหตุได้</small></label><p className="muted">For unilateral exercises, allow 15–30 seconds to switch sides, then take the listed rest after both sides. Power drills: reset each repetition; stop when speed or control deteriorates.</p><p className="rest-guidance"><b>พักประมาณ {ex.restLabel}</b> · กะเวลาได้ พักต่อจนหายใจและฟอร์มพร้อม</p>{old.length>0&&<details className="old-lifts"><summary>บันทึกกิโล/ครั้งเดิมของวันนี้</summary>{old.map(([key,value])=><p key={key}>เซ็ต {Number(key.split('-').at(-1))+1}: {value||'ยังไม่กรอก'}</p>)}</details>}{entry.done.includes(ex.id)&&actual===undefined&&<p className="muted">เคยติ๊กว่าทำครบไว้ แต่ยังไม่มีจำนวนเซ็ตที่กรอก</p>}</AccordionContent></AccordionItem>})}
 </Accordion></div>
}
