import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,stat} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
const root=fileURLToPath(new URL('../dist/',import.meta.url));
const server=createServer(async(req,res)=>{try{let name=decodeURIComponent(new URL(req.url,'http://local').pathname).replace(/^\/court-coach\//,'/');if(name.endsWith('/'))name+='index.html';const file=path.resolve(root,'.'+name);if(!file.startsWith(root))throw Error();const data=await readFile(file);const ext=path.extname(file);res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.jpg':'image/jpeg'})[ext]??'text/plain');res.end(data)}catch{res.writeHead(404);res.end('Not found')}});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
try{const origin='http://127.0.0.1:'+server.address().port;const images=JSON.parse(await readFile(new URL('../lib/exercise-images.json',import.meta.url),'utf8'));for(const mount of ['/','/court-coach/']){const url=origin+mount,r=await fetch(url);assert.equal(r.status,200);const html=await r.text();assert(html.includes('width=device-width'));const refs=[...html.matchAll(/(?:src|href)="([^"#]+)"/g)].map(m=>m[1]);refs.push(...Object.values(images).flatMap(x=>[...x.images,...(x.earlyImages||[]),...(x.laterImages||[])]),'./exercises/LICENSE.txt','./.nojekyll');await Promise.all(refs.map(async ref=>{assert(ref.startsWith('./'));const asset=await fetch(new URL(ref,url));assert.equal(asset.status,200,ref);assert((await asset.arrayBuffer()).byteLength>0||ref==='./.nojekyll')}));const jsref=refs.find(x=>x.endsWith('.js'));const js=await (await fetch(new URL(jsref,url))).text();assert(!js.includes('/api/coach'));assert(!js.includes('signin-with-chatgpt'));assert.equal((await fetch(origin+mount+'api/coach')).status,404);console.log('Static HTTP and all assets passed at '+mount)}const files=await stat(path.join(root,'index.html'));assert(files.size>0)}finally{await new Promise(resolve=>server.close(resolve))}
